language: go

go:
        - 1.4
before_install:
        - git clone git://github.com/jedisct1/libsodium.git
        - ( cd libsodium; ./autogen.sh; ./configure; make check; sudo make install; sudo ldconfig )
        - git clone git://github.com/zeromq/libzmq.git
        - ( cd zeromq4-x; ./autogen.sh; ./configure; make check; sudo make install; sudo ldconfig )
        - git clone git://github.com/zeromq/czmq.git
        - ( cd czmq; ./autogen.sh; ./configure; make check; sudo make install; sudo ldconfig )
script:
        - go get github.com/zeromq/goczmq
        - go test -v .
